version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-production-routine:
        dependency-type: production
        update-types: [minor, patch]
      npm-development-routine:
        dependency-type: development
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-routine:
        update-types: [minor, patch]
